# Generated by Django 4.0.4 on 2022-05-21 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosPagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Metodo de pago')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion de pago')),
                ('siglas', models.CharField(max_length=20, verbose_name='Siglas')),
                ('mensaje_guia', models.TextField(verbose_name='Mensaje que ve el usuario')),
            ],
            options={
                'verbose_name': 'Metodo de Pago',
                'verbose_name_plural': 'Metodo de Pagos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la reaccion')),
            ],
            options={
                'verbose_name': 'Reaccion',
                'verbose_name_plural': 'Reacciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Redes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la red social')),
            ],
            options={
                'verbose_name': 'Rede',
                'verbose_name_plural': 'Redes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UsersTelegram',
            fields=[
                ('estado', models.BooleanField(default=False, verbose_name='Estado del Usuario')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('client_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de telegram del usuario')),
                ('referido', models.IntegerField(blank=True, null=True, verbose_name='Referido')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Usuario')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion del usuario')),
                ('foto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ruta de la foto')),
                ('ultimomsg', models.CharField(blank=True, max_length=50, null=True, verbose_name='ultimo sms')),
            ],
            options={
                'verbose_name': 'User Telegram',
                'verbose_name_plural': 'Users Telegram',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='UsersReaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('actor', models.IntegerField(verbose_name='El que reacciona')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_telegram.userstelegram')),
                ('id_reaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_telegram.reaccion')),
            ],
            options={
                'verbose_name': 'UsersReaccion',
                'verbose_name_plural': 'UsersReacciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UsersMetodosPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_telegram.metodospagos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_telegram.userstelegram')),
            ],
        ),
        migrations.CreateModel(
            name='UserRedes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('username', models.CharField(max_length=100, verbose_name='ruta de la red social')),
                ('redes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_telegram.redes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_telegram.userstelegram')),
            ],
            options={
                'verbose_name': 'UserRede',
                'verbose_name_plural': 'UserRedes',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('fotos_galeria', models.CharField(max_length=100, verbose_name='Ruta de la foto')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_telegram.userstelegram')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
                'ordering': ['id'],
            },
        ),
    ]
