# Generated by Django 4.0.4 on 2022-05-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redes',
            name='url',
            field=models.URLField(default='', verbose_name='Direccion de la red socioal'),
        ),
    ]
