# Generated by Django 4.0.4 on 2022-05-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0002_redes_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redes',
            name='url',
            field=models.URLField(verbose_name='Direccion de la red socioal'),
        ),
    ]
