# Generated by Django 4.0.4 on 2022-05-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0003_alter_redes_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstelegram',
            name='saldo_ref',
            field=models.FloatField(default=0, verbose_name='Saldo de referidos'),
        ),
    ]
