# Generated by Django 4.0.4 on 2022-05-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0004_userstelegram_saldo_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmetodospagos',
            name='fecha_pago',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Pago'),
        ),
    ]
