# Generated by Django 4.0.4 on 2022-05-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0005_usersmetodospagos_fecha_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersmetodospagos',
            options={'verbose_name': 'User Metodo Pago', 'verbose_name_plural': 'Users Metodos Pagos'},
        ),
        migrations.AlterField(
            model_name='usersmetodospagos',
            name='fecha_pago',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Pago'),
        ),
    ]
