# Generated by Django 4.0.4 on 2022-05-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0006_alter_usersmetodospagos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmetodospagos',
            name='fecha_pago',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Pago'),
        ),
    ]
