# Generated by Django 4.0.4 on 2022-05-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0007_alter_usersmetodospagos_fecha_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersmetodospagos',
            options={'ordering': ['fecha_pago'], 'verbose_name': 'User Metodo Pago', 'verbose_name_plural': 'Users Metodos Pagos'},
        ),
        migrations.AddField(
            model_name='usersreaccion',
            name='message',
            field=models.CharField(default='', max_length=200, verbose_name='Publicacion id'),
        ),
    ]
