# Generated by Django 4.0.4 on 2022-05-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0009_alter_usersreaccion_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersreaccion',
            name='message',
            field=models.IntegerField(max_length=200, verbose_name='Publicacion id'),
        ),
    ]
