# Generated by Django 4.0.4 on 2022-05-22 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0010_alter_usersreaccion_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersreaccion',
            name='client_id',
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('fecha_publicacion', models.DateField(auto_now=True, verbose_name='Fecha de la publicacion')),
                ('message', models.IntegerField(max_length=200, primary_key=True, serialize=False, verbose_name='Publicacion id')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_telegram.userstelegram')),
            ],
        ),
        migrations.AlterField(
            model_name='usersreaccion',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_telegram.publicacion'),
        ),
    ]
