# Generated by Django 4.0.4 on 2022-05-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0011_remove_usersreaccion_client_id_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['fecha_publicacion'], 'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicacionnes'},
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='message',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Publicacion id'),
        ),
    ]
