# Generated by Django 4.0.4 on 2022-05-27 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0014_alter_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstelegram',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user_telegram.planes'),
        ),
    ]
