# Generated by Django 4.0.4 on 2022-05-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0015_userstelegram_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planes',
            old_name='descriptcion',
            new_name='descripcion',
        ),
    ]
