# Generated by Django 4.0.4 on 2022-05-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0016_rename_descriptcion_planes_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstelegram',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='planes',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion del plan'),
        ),
    ]
