# Generated by Django 4.0.4 on 2022-05-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0017_rename_description_userstelegram_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodospagos',
            name='valor_cambio',
            field=models.FloatField(default=1, verbose_name='Valor del cambio'),
        ),
    ]
