# Generated by Django 4.0.4 on 2022-06-01 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0018_metodospagos_valor_cambio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstelegram',
            name='saldo_ref',
        ),
    ]
