# Generated by Django 4.0.4 on 2022-06-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0019_remove_userstelegram_saldo_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstelegram',
            name='saldo_ref',
            field=models.FloatField(default=0, verbose_name='Saldo de referidos'),
        ),
    ]
