# Generated by Django 4.0.4 on 2022-06-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_telegram', '0020_userstelegram_saldo_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstelegram',
            name='saldo_ref',
        ),
        migrations.AddField(
            model_name='userstelegram',
            name='saldo_cup',
            field=models.FloatField(default=0, verbose_name='Saldo de referidos en cup'),
        ),
        migrations.AddField(
            model_name='userstelegram',
            name='saldo_mlc',
            field=models.FloatField(default=0, verbose_name='Saldo de referidos en mlc'),
        ),
        migrations.AddField(
            model_name='userstelegram',
            name='saldo_movil',
            field=models.FloatField(default=0, verbose_name='Saldo de referidos en movil'),
        ),
        migrations.AddField(
            model_name='userstelegram',
            name='saldo_usd',
            field=models.FloatField(default=0, verbose_name='Saldo de referidos en usd'),
        ),
    ]
